FROM rocker/r-ver:3.6.3



# #install needed libraries
RUN   apt update && \
	  apt install -y libcurl4-openssl-dev libz-dev libtool python-dev libbz2-dev liblzma-dev libxml2-dev libssl-dev && rm -rf /var/lib/apt/lists/* && \
	  R -e "install.packages(c('shiny','shinyFiles','shinydashboard','shinyWidgets','fastcluster','VennDiagram','data.table','RColorBrewer','ppcor','inline','BiocManager','RCurl'),repos='http://cran.us.r-project.org')" && \
      R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install(version = bioCversion,ask=F)" && \
      R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('GenomicRanges', version = bioCversion,ask=FALSE)" && \
      R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('Rsamtools', version = bioCversion,ask=FALSE)" && \
      R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('rtracklayer', version = bioCversion,ask=FALSE)"
    
# #install database libraries  

 RUN     R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('BSgenome.Mmusculus.UCSC.mm10',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('BSgenome.Mmusculus.UCSC.mm9',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('BSgenome.Hsapiens.UCSC.hg19',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('BSgenome.Hsapiens.UCSC.hg38',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('org.Hs.eg.db',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('org.Mm.eg.db',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('TxDb.Hsapiens.UCSC.hg19.knownGene',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('TxDb.Hsapiens.UCSC.hg38.knownGene',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('TxDb.Mmusculus.UCSC.mm10.knownGene',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('TxDb.Mmusculus.UCSC.mm9.knownGene',version = bioCversion,ask=FALSE)" && \
         R -e "bioCversion=as.character(tools:::.BioC_version_associated_with_R_version()); BiocManager::install('bamsignals',version = bioCversion,ask=FALSE)"

EXPOSE 6060
#copy the folder of the source code of ChroKit in the home directory
COPY ./ChroKit_lowmem/source /home/ChroKit

#the following script (start_chrokit_docker.sh) contains this:
#! /bin/bash
# cd /home/ChroKit/
# echo "$@"
# Rscript shinyapp.r

COPY ./start_chrokit_docker.sh /home/start_chrokit_docker.sh
RUN ["chmod","+x","/home/start_chrokit_docker.sh"]
RUN ["chmod","-R","777","/home/"]
ENTRYPOINT ["/home/start_chrokit_docker.sh"]
